
// ## --------- STEPS REGISTER --------- ## //
export const STEP_REGISTER_PROFILE = 0;
export const STEP_REGISTER_ADDRESS = 1;

// ## --------- SELECTS --------- ## //
export const statesForSelect = [
	{ value: 'AC', label: 'Acre' },
	{ value: 'AL', label: 'Alagoas' },
	{ value: 'AP', label: 'Amapá' },
	{ value: 'AM', label: 'Amazonas' },
	{ value: 'BA', label: 'Bahia' },
	{ value: 'CE', label: 'Ceará' },
	{ value: 'DF', label: 'Distrito Federal' },
	{ value: 'ES', label: 'Espírito Santo' },
	{ value: 'GO', label: 'Goiás' },
	{ value: 'MA', label: 'Maranhão' },
	{ value: 'MT', label: 'Mato Grosso' },
	{ value: 'MS', label: 'Mato Grosso do Sul' },
	{ value: 'MG', label: 'Minas Gerais' },
	{ value: 'PA', label: 'Pará' },
	{ value: 'PB', label: 'Paraíba' },
	{ value: 'PR', label: 'Paraná' },
	{ value: 'PE', label: 'Pernambuco' },
	{ value: 'PI', label: 'Piauí' },
	{ value: 'RJ', label: 'Rio de Janeiro' },
	{ value: 'RN', label: 'Rio Grande do Norte' },
	{ value: 'RS', label: 'Rio Grande do Sul' },
	{ value: 'RO', label: 'Rondônia' },
	{ value: 'RR', label: 'Roraima' },
	{ value: 'SC', label: 'Santa Catarina' },
	{ value: 'SP', label: 'São Paulo' },
	{ value: 'SE', label: 'Sergipe' },
	{ value: 'TO', label: 'Tocantins' }
]

export const countriesForSelect = [
    { value: "AF", label: "Afeganistão"},
    { value: "ZA", label: "África do Sul"},
    { value: "DE", label: "Alemanha"},
    { value: "AO", label: "Angola"},
    { value: "SA", label: "Arábia Saudita"},
    { value: "DZ", label: "Argélia"},
    { value: "AR", label: "Argentina"},
    { value: "AM", label: "Armênia"},
    { value: "AU", label: "Austrália"},
    { value: "AT", label: "Áustria"},
    { value: "BS", label: "Bahamas"},
    { value: "BE", label: "Bélgica"},
    { value: "BM", label: "Bermudas"},
    { value: "BO", label: "Bolívia"},
    { value: "BA", label: "Bósnia"},
    { value: "BR", label: "Brasil"},
    { value: "BG", label: "Bulgária"},
    { value: "CM", label: "Camarões"},
    { value: "CA", label: "Canadá"},
    { value: "KZ", label: "Cazaquistão"},
    { value: "CL", label: "Chile"},
    { value: "CN", label: "China"},
    { value: "CY", label: "Chipre"},
    { value: "SG", label: "Cingapura"},
    { value: "CO", label: "Colômbia"},
    { value: "KP", label: "Coréia do Norte"},
    { value: "KR", label: "Coréia do Sul"},
    { value: "CI", label: "Costa do Marfim"},
    { value: "CR", label: "Costa Rica"},
    { value: "HR", label: "Croácia"},
    { value: "CU", label: "Cuba"},
    { value: "DK", label: "Dinamarca"},
    { value: "EG", label: "Egito"},
    { value: "SV", label: "El Salvador"},
    { value: "AE", label: "Emirados Árabes"},
    { value: "EC", label: "Equador"},
    { value: "SK", label: "Eslováquia"},
    { value: "SI", label: "Eslovênia"},
    { value: "ES", label: "Espanha"},
    { value: "US", label: "Estados Unidos"},
    { value: "EE", label: "Estônia"},
    { value: "ET", label: "Etiópia"},
    { value: "PH", label: "Filipinas"},
    { value: "FI", label: "Finlândia"},
    { value: "FR", label: "França"},
    { value: "GH", label: "Gana"},
    { value: "GE", label: "Geórgia"},
    { value: "GB", label: "Grã-Bretanha"},
    { value: "GR", label: "Grécia"},
    { value: "GL", label: "Groelândia"},
    { value: "GP", label: "Guadalupe"},
    { value: "GT", label: "Guatemala"},
    { value: "GY", label: "Guiana"},
    { value: "GN", label: "Guiné"},
    { value: "HT", label: "Haiti"},
    { value: "NL", label: "Holanda"},
    { value: "HN", label: "Honduras"},
    { value: "HK", label: "Hong Kong"},
    { value: "HU", label: "Hungria"},
    { value: "YE", label: "Iêmen"},
    { value: "IN", label: "índia"},
    { value: "ID", label: "Indonésia"},
    { value: "IR", label: "Irã"},
    { value: "IQ", label: "Iraque"},
    { value: "IE", label: "Irlanda"},
    { value: "IS", label: "Islândia"},
    { value: "IL", label: "Israel"},
    { value: "IT", label: "Itália"},
    { value: "JM", label: "Jamaica"},
    { value: "JP", label: "Japão"},
    { value: "LB", label: "Líbano"},
    { value: "LY", label: "Líbia"},
    { value: "LT", label: "Lituânia"},
    { value: "MY", label: "Malásia"},
    { value: "MA", label: "Marrocos"},
    { value: "MX", label: "México"},
    { value: "MZ", label: "Moçambique"},
    { value: "MC", label: "Mônaco"},
    { value: "NP", label: "Nepal"},
    { value: "NI", label: "Nicarágua"},
    { value: "NG", label: "Nigéria"},
    { value: "NO", label: "Noruega"},
    { value: "NZ", label: "Nova Zelândia"},
    { value: "PA", label: "Panamá"},
    { value: "PK", label: "Paquistão"},
    { value: "PY", label: "Paraguai"},
    { value: "PE", label: "Peru"},
    { value: "PL", label: "Polônia"},
    { value: "PR", label: "Porto Rico"},
    { value: "PT", label: "Portugal"},
    { value: "QA", label: "Qatar"},
    { value: "CZ", label: "República Tcheca"},
    { value: "RO", label: "Romênia"},
    { value: "RU", label: "Rússia"},
    { value: "SN", label: "Senegal"},
    { value: "RS", label: "Sérvia"},
    { value: "SY", label: "Síria"},
    { value: "SE", label: "Suécia"},
    { value: "CH", label: "Suíça"},
    { value: "TH", label: "Tailândia"},
    { value: "TT", label: "Trinidad and Tobago"},
    { value: "TN", label: "Tunísia"},
    { value: "TR", label: "Turquia"},
    { value: "UA", label: "Ucrânia"},
    { value: "UY", label: "Uruguai"},
    { value: "VA", label: "Vaticano"},
    { value: "VE", label: "Venezuela"},
    { value: "VN", label: "Vietnã"}
]
